sudo: required

language: ruby
rvm:
  - 2.7

before_install:
  - gem install bundler

git:
  depth: false

script:
- COMMIT_RANGE="$(echo ${TRAVIS_COMMIT_RANGE//.../..})"
- CHANGED_FILES="$(git diff --diff-filter=MA --name-only ${COMMIT_RANGE})"
- echo $CHANGED_FILES
- CHANGED_RMDFILES="$(git diff --diff-filter=MA --name-only ${COMMIT_RANGE} -- | grep '.Rmd')"
