# Site settings
title: INFO550
subtitle: Data Science Toolkit
description: |
    This course is an elective for Masters and PhD students at 
    <a href='https://www.sph.emory.edu/'>Emory University Rollins School of Public Health</a>. 
    The course covers some fundamental tools used in modern (reproducible) data science. 
    Together, these tools 
    provide the ability to develop fully reproducible pipelines for data 
    analysis. By the end of the course students will have learned the tools necessary to: 
    develop reproducible workflows collaboratively (using version control based on Git/GitHub), 
    execute these workflows on a local computer (using command line operations, RMarkdown, 
    and GNU Makefiles), execute the workflows in a containerized environment allowing 
    end-to-end reproducibility (using Docker), and execute the workflow in a cloud 
    environment (using Amazon Web Services EC2 and S3 services). Along the way, we will 
    cover a few other tools for data science including best coding practices, basic python, 
    software unit testing, and continuous integration services. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://benkeser.github.io/course-website" # the base hostname & protocol for your site

# host the syllabus on google docs
# File: Publish to Web
syllabus_url: "https://docs.google.com/document/d/e/2PACX-1vTPKXf13lffq2wiZuAB11OnPJQe1pNXvPEjhxiceAk5Bs164L0wyQzmksjeotB_VjT-xf_TY-zHqimS/pub?embedded=true"
githubdir: "benkeser/info550"

# Author/user information
email: benkeser@emory.edu
twitter_username: TODO
github_username:  benkeser
authorurl: "http://TODO.com"
address: |
    Emory University
    Department of Biostatistics and Bioinformatics
    1518 Clifton Rd. NE
    Atlanta, GA 30322

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
